module.exports = { 
  id: '14299057',
  displayName: 'Nadir Fayazov',
  username: 'nfayazov',
  profileUrl: 'https://github.com/nfayazov',
  photos: [ { value: 'https://avatars3.githubusercontent.com/u/14299057?v=4' } ],
  provider: 'github',
  _raw: '{"login":"nfayazov","id":14299057,"node_id":"MDQ6VXNlcjE0Mjk5MDU3","avatar_url":"https://avatars3.githubusercontent.com/u/14299057?v=4","gravatar_id":"","url":"https://api.github.com/users/nfayazov","html_url":"https://github.com/nfayazov","followers_url":"https://api.github.com/users/nfayazov/followers","following_url":"https://api.github.com/users/nfayazov/following{/other_user}","gists_url":"https://api.github.com/users/nfayazov/gists{/gist_id}","starred_url":"https://api.github.com/users/nfayazov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nfayazov/subscriptions","organizations_url":"https://api.github.com/users/nfayazov/orgs","repos_url":"https://api.github.com/users/nfayazov/repos","events_url":"https://api.github.com/users/nfayazov/events{/privacy}","received_events_url":"https://api.github.com/users/nfayazov/received_events","type":"User","site_admin":false,"name":"Nadir Fayazov","company":null,"blog":"","location":"San Luis Obispo, CA","email":null,"hireable":true,"bio":null,"public_repos":18,"public_gists":0,"followers":1,"following":12,"created_at":"2015-09-15T18:08:22Z","updated_at":"2018-09-02T23:08:23Z"}',
  _json:
   { login: 'nfayazov',
     id: 14299057,
     node_id: 'MDQ6VXNlcjE0Mjk5MDU3',
     avatar_url: 'https://avatars3.githubusercontent.com/u/14299057?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/nfayazov',
     html_url: 'https://github.com/nfayazov',
     followers_url: 'https://api.github.com/users/nfayazov/followers',
     following_url: 'https://api.github.com/users/nfayazov/following{/other_user}',
     gists_url: 'https://api.github.com/users/nfayazov/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/nfayazov/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/nfayazov/subscriptions',
     organizations_url: 'https://api.github.com/users/nfayazov/orgs',
     repos_url: 'https://api.github.com/users/nfayazov/repos',
     events_url: 'https://api.github.com/users/nfayazov/events{/privacy}',
     received_events_url: 'https://api.github.com/users/nfayazov/received_events',
     type: 'User',
     site_admin: false,
     name: 'Nadir Fayazov',
     company: null,
     blog: '',
     location: 'San Luis Obispo, CA',
     email: null,
     hireable: true,
     bio: null,
     public_repos: 18,
     public_gists: 0,
     followers: 1,
     following: 12,
     created_at: '2015-09-15T18:08:22Z',
     updated_at: '2018-09-02T23:08:23Z' } 
   }