const path = require('path').join(__dirname, '../../public/');
const ts = require('unix-timestamp');
const { Workspace } = require('../db/models/workspace');
const User = require('../db/models/user');

module.exports = function(app, passport) {

   function isLoggedIn (req, res, next) {
		if (req.isAuthenticated()) {
			return next();
		} else {
			res.redirect('/login');
		}
	};

   app.route('/')
      .get(isLoggedIn, function (req, res) {
         res.redirect('/profile');
      });

   app.route('/login')
      .get((req, res) => {
         res.render(path + 'views/login.hbs');
	   });

   app.route('/workspace-test')
      .get(isLoggedIn, function (req, res) {
         res.render(path + 'views/workspace.hbs', { filename: 'test.js' });
      });
      
   app.route('/profile')
      .get(isLoggedIn, function (req, res) {
         getWorkspacesByGithubId(req.user.github.id, res).then((workspaces) => {
            res.render(path + 'views/profile.hbs', {
               name: req.user.github.displayName,
               username: req.user.github.username,
               avatar_url: req.user.github.avatar_url,
               bio: req.user.github.bio,
               workspaces: workspaces
            });
         }, (e) => {
            res.status(404).send(e);
         });
      });

   // Add this to some util file
   let getWorkspacesByGithubId = (id, res) => {
      return User.findOne({ 'github.id': id }).then((user) => {
         return Promise.all(user.workspaces.map((ws) => {
            return Workspace.findById(ws).then((wsRecord) => {
               return {name: wsRecord.name, _id: wsRecord._id };
            });
         }))
      }, (e) => {
         res.status(404).send(e);
      });
   };

   app.route('/auth/github')   
      .get(passport.authenticate('github'), (req, res) => {
         if (process.env.NODE_ENV === 'development')
            res.redirect('/profile');
      });

   app.route('/auth/github/callback')
      .get(passport.authenticate('github', { failureRedirect: '/login' } ),
         function(req, res) {
            res.redirect('/profile');
      });

   app.route('/api/:id')
      .get(isLoggedIn, function(req,res) {
         res.json(req.user.github);
      });

   app.route('/new')
      .post(isLoggedIn, function(req,res) {
         let workspace = new Workspace({
            name: req.body.name,
            description: req.body.description,
            filename: req.body.filename,
            createdAt: ts.now(),
            createdBy: req.user.github.id
         });
         // TODO: Refactor
         workspace.save().then((doc) => {
            // Add workspace to user profile
            User.findOne({ 'github.id' : req.user.github.id}).then((user) => {
               user.workspaces.push(doc._id);
               user.save().then((updatedUser) => {
                     res.send(updatedUser);
               }, (e) => {
                  res.status(404).send(e)
               });
            }, (e) => {
               res.status(404).send(e);
            });
            res.send(doc._id);
         }, (e) => {
            res.status(400).send(e);
         });
                  
      })
      .get(isLoggedIn, function(req, res) {
         res.sendFile(path + 'newWorkspace.html');
      });
      
   app.route('/workspace/:id')
      .get(isLoggedIn, (req, res) => {
         Workspace.findById(req.params.id).then((ws) => {
            res.render(path + 'views/workspace.hbs', { filename: ws.filename });
         }, (e) => {
            res.status(404).send({error: 'Workspace not found'});
         });
      });  

   module.exports.getWorkspacesByGithubId = getWorkspacesByGithubId;
   // POST /workspace 
   // {text:"func main()",
   // users: "user1", "user3", "user5"
   // id: "_autogeneratedId",
   // commitedAt: 424245454543,
   // commitedBy: "user1"}

   // UPDATE /workspace/autegeneratedId 
}